/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChordproRouteImport } from './routes/chordpro'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LegalRouteImport } from './routes/legal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChordproRoute = ChordproRouteImport.update({
  id: '/chordpro',
  path: '/chordpro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chordpro': typeof ChordproRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chordpro': typeof ChordproRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chordpro': typeof ChordproRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chordpro' | '/contact' | '/legal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chordpro' | '/contact' | '/legal'
  id: '__root__' | '/' | '/chordpro' | '/contact' | '/legal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChordproRoute: typeof ChordproRoute
  ContactRoute: typeof ContactRoute
  LegalRoute: typeof LegalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chordpro': {
      id: '/chordpro'
      path: '/chordpro'
      fullPath: '/chordpro'
      preLoaderRoute: typeof ChordproRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChordproRoute: ChordproRoute,
  ContactRoute: ContactRoute,
  LegalRoute: LegalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
